### ISSUE TITLE
Create a new release for 0.2.0

### ISSUE THREAD

**Issue by anweiss** [docker/oscalkit#38]
Tracking for the 0.2.0 release.

**Comment by anweiss** [comment]
@minhaj10p I think once #51, #52, #58 and #64 are merged, we can cut a 0.2.0 release ... thoughts?

**Comment by asadullah-yousuf-10p** [comment]
> @minhaj10p I think once #51, #52, #58 and #64 are merged, we can cut a 0.2.0 release ... thoughts?

Sounds good @anweiss

**Comment by minhaj10p** [comment]
@anweiss yes, I'll shortly be creating another PR which will handle the sub control thats getting omitted with no control on top. Once thats merged. We'll be good I guess.

**Comment by anweiss** [comment]
Thanks @minhaj10p. Just one comment on #77 but otherwise, works for me.

**Comment by minhaj10p** [comment]
#77 the comment you added is resolved now. Please review when you get time and merge. Thanks!
