### ISSUE TITLE
Generated implementation struct needs to include component definition ID 

### ISSUE THREAD

**Issue by haroonKhan-10p** [docker/oscalkit#50]
The oscalkit generated implementation struct does not have componenetDefinition ID as of now, which is essential for patching implementation against a certain component.

**Comment by haroonKhan-10p** [comment]
From the header of our Control Mapping our component ID looks like this for now:
`component ID: cpe:2.3:a:docker:ucp:3.2.0:*:*:*:*:*:*:*`
I am gonna extract `cpe:2.3:a:docker:ucp:3.2.0`. Or do we need to use a UUID here?

**Comment by anweiss** [comment]
@haroonKhan-10p yes, please extract the CPE value.

**Comment by anweiss** [comment]
Addressed via #51
