### ISSUE TITLE
Oscalkit failing to parse profile where an https import, imports a relative path. 

### ISSUE THREAD

**Issue by farhan-khan30** [docker/oscalkit#70]
Related to: #57 

When executing `oscalkit generate code` and processing a profile that has been imported using an `https://` link, if that profile internally imports a profile/catalog relatively, the path is resolved incorrectly by appending the current system relative path to the `https://` path of the parent profile that has imported the catalog/profile. The problem lies in the parentPath handing in:
https://github.com/docker/oscalkit/blob/c5a92172971fa7ea1ccfdf7b08f67ed5bae53683/generator/profile.go#L44

cc: @minhaj10p @anweiss

**Comment by anweiss** [comment]
Good catch @farhan-khan3.

**Comment by minhaj10p** [comment]
addressed in #71 
@farhan-khan30 @anweiss

**Comment by farhan-khan30** [comment]
Verified fix in #71. Closing.
@anweiss @minhaj10p
