### ISSUE TITLE
Guidance type should rather be an []string instead of string 

### ISSUE THREAD

**Issue by aitchkhan** [docker/oscalkit#74]
The guidance present in [fedramp baseline](https://github.com/usnistgov/OSCAL/tree/master/content/fedramp.gov) `implementsProfile[].Parameters[]` are an array of multiple `p` tag.
IMHO, guidance in `Parameter` struct should be of type `[]string` rather than `string`.
https://github.com/docker/oscalkit/blob/42bb04d0ffeec2f1979f895ebfc8ea9819dc9223/types/oscal/implementation/implementation.go#L39

**Comment by anweiss** [comment]
Fixed by #78.
