### ISSUE TITLE
Failing test on fedramp profile

### ISSUE THREAD

**Issue by farhan-khan30** [docker/oscalkit#83]
Tests are failing on Fedramp profile with a panic: `runtime error: index out of range`
The probable culprit for modifying the part incorrectly is:
https://github.com/docker/oscalkit/blob/4d3ebce31f13655d9ab0820a5be6b876d4a46e4e/generator/manipulation.go#L100

cc: @minhaj10p @anweiss

**Comment by farhan-khan30** [comment]
Fixed in  #84 
Awaiting review and merge
@anweiss

**Comment by anweiss** [comment]
#84 has been merged.
